server:
  port:8080

spring:
  datasource:
    username: root
    password: 9959273466@m
    url: jdbc:mysql://localhost:3306/springDbs
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
